In [11]:
'''>>>>> start CodeP4.1F23
V.P. Carey ME249, Fall 2023
Keras Neural Network Modeling '''
#import useful packages
import keras
import pandas as pd
from keras.models import Sequential
import numpy as np
import keras.backend as kb
import tensorflow as tf
#the following 2 lines are only needed for Mac OS machines
import os
os.environ['KMP_DUPLICATE_LIB_OK']='True'
# define meadian values of input variables - add your values here

import statistics
xdata = []
ydata = []
#xdata.append([ Di(m), qoflux (kW/m^2), mdot (kg/s)])

xdata.append([0.008, 550, 0.06157])
xdata.append([0.008, 651, 0.07269])
xdata.append([0.008, 750, 0.08396])
xdata.append([0.008, 850, 0.09347])
xdata.append([0.008, 950, 0.10635])
xdata.append([0.008, 1050, 0.11521])
xdata.append([0.008, 1150, 0.1287])
xdata.append([0.008, 850, 0.09516])
xdata.append([0.008, 550, 0.04398])
xdata.append([0.008, 750, 0.05997])
xdata.append([0.008, 950, 0.07596])
xdata.append([0.008, 1050, 0.08343])
xdata.append([0.008, 1150, 0.0919])
xdata.append([0.008, 850, 0.06797])
xdata.append([0.008, 550, 0.0342])
xdata.append([0.008, 750, 0.04664])
xdata.append([0.008, 950, 0.05908])
xdata.append([0.008, 1150, 0.0715])
xdata.append([0.008, 850, 0.05286])
xdata.append([0.011, 550, 0.0846])
xdata.append([0.011, 750, 0.1154])
xdata.append([0.011, 950, 0.1462])
xdata.append([0.011, 1150, 0.177])
xdata.append([0.011, 850, 0.1308])
xdata.append([0.011, 550, 0.06047])
xdata.append([0.011, 750, 0.08246])
xdata.append([0.011, 950, 0.1044])
xdata.append([0.011, 1050, 0.1134])
xdata.append([0.011, 1150, 0.1264])
xdata.append([0.011, 850, 0.0934])
xdata.append([0.011, 550, 0.047])
xdata.append([0.011, 750, 0.06413])
xdata.append([0.011, 950, 0.08124])
xdata.append([0.011, 1150, 0.09834])
xdata.append([0.011, 850, 0.072691])
xdata.append([0.011, 700, 0.087196])
xdata.append([0.013, 550, 0.10005])
xdata.append([0.013, 750, 0.13644])
xdata.append([0.013, 950, 0.17282])
xdata.append([0.013, 1150, 0.2092])
xdata.append([0.013, 850, 0.15463])
xdata.append([0.013, 550, 0.07147])
xdata.append([0.013, 750, 0.09745])
xdata.append([0.013, 950, 0.12344])
xdata.append([0.013, 1050, 0.13302])
xdata.append([0.013, 1150, 0.1494])
xdata.append([0.013, 850, 0.11045])
xdata.append([0.013, 550, 0.05558])
xdata.append([0.013, 750, 0.0758])
xdata.append([0.013, 950, 0.09601])
xdata.append([0.013, 1150, 0.1162])
xdata.append([0.013, 850, 0.0859])

#ydata.append([ exit quality, max wall temperature (deg C)])
ydata.append([0.525, 306.7])
ydata.append([0.525, 298.5])
ydata.append([0.525, 294.5])
ydata.append([0.525, 290.2])
ydata.append([0.524, 286.9])
ydata.append([0.524, 284.1])
ydata.append([0.525, 281.7])
ydata.append([0.524, 290.3])
ydata.append([0.734, 307.9])
ydata.append([0.735, 295.5])
ydata.append([0.735, 287.8])
ydata.append([0.735, 285.0])
ydata.append([0.735, 282.5])
ydata.append([0.734, 291.3])
ydata.append([ 0.945, 308.6])
ydata.append([0.945, 296.2])
ydata.append([0.945, 288.5])
ydata.append([0.945, 283.1])
ydata.append([0.945, 291.9])
ydata.append([ 0.525, 328.0])
ydata.append([0.525, 311.2])
ydata.append([0.525, 300.8])
ydata.append([0.525, 293.6])
ydata.append([0.525, 305.5])
ydata.append([0.735, 329.6])
ydata.append([0.735, 312.6])
ydata.append([0.735, 302.0])
ydata.append([0.735, 299.4])
ydata.append([0.735, 294.8])
ydata.append([0.735, 306.8])
ydata.append([ 0.945, 330.7])
ydata.append([0.945, 313.6])
ydata.append([0.944, 302.9])
ydata.append([0.945, 295.6])
ydata.append([0.944, 307.7])
ydata.append([0.734, 324.7])
ydata.append([0.525, 342.2])
ydata.append([0.524, 322.3])
ydata.append([0.524, 310.0])
ydata.append([0.525, 301.6])
ydata.append([0.524, 315.5])
ydata.append([0.734, 344.1])
ydata.append([0.735, 324.0])
ydata.append([0.735, 311.5])
ydata.append([0.735, 306.3])
ydata.append([0.735, 302.9])
ydata.append([0.734, 317.1])
ydata.append([0.945, 345.3])
ydata.append([0.944, 325.1])
ydata.append([0.944, 312.5])
ydata.append([0.945, 303.9])
ydata.append([0.945, 318.2])
xarray= np.array(xdata)
yarray= np.array(ydata)
print (xdata)
print (xarray)
print (ydata)
print (yarray)

#convert to:
# median values of output variables
ND=len(xarray)
Taall = [row[0] for row in xdata]
Tamed=statistics.median(Taall)
IDall = [row[1] for row in xdata]
IDmed=statistics.median(IDall)
RLall = [row[2] for row in xdata]
RLmed=statistics.median(RLall)

VLall = [row[0] for row in ydata]
VLmed=statistics.median(VLall)
Wdall = [row[1] for row in ydata]
Wdmed=statistics.median(Wdall)

xdata = []
ydata = []
for i in range(ND):
    xdata.append([xarray[i,0]/Tamed,xarray[i,1]/IDmed,xarray[i,2]/RLmed])
    ydata.append([yarray[i,0]/VLmed,yarray[i,1]/Wdmed])

xarray= np.array(xdata)
yarray= np.array(ydata)

#print (yarray)

data_inputs = np.array(xdata)
data_outputs = np.array(ydata)

[[0.008, 550, 0.06157], [0.008, 651, 0.07269], [0.008, 750, 0.08396], [0.008, 850, 0.09347], [0.008, 950, 0.10635], [0.008, 1050, 0.11521], [0.008, 1150, 0.1287], [0.008, 850, 0.09516], [0.008, 550, 0.04398], [0.008, 750, 0.05997], [0.008, 950, 0.07596], [0.008, 1050, 0.08343], [0.008, 1150, 0.0919], [0.008, 850, 0.06797], [0.008, 550, 0.0342], [0.008, 750, 0.04664], [0.008, 950, 0.05908], [0.008, 1150, 0.0715], [0.008, 850, 0.05286], [0.011, 550, 0.0846], [0.011, 750, 0.1154], [0.011, 950, 0.1462], [0.011, 1150, 0.177], [0.011, 850, 0.1308], [0.011, 550, 0.06047], [0.011, 750, 0.08246], [0.011, 950, 0.1044], [0.011, 1050, 0.1134], [0.011, 1150, 0.1264], [0.011, 850, 0.0934], [0.011, 550, 0.047], [0.011, 750, 0.06413], [0.011, 950, 0.08124], [0.011, 1150, 0.09834], [0.011, 850, 0.072691], [0.011, 700, 0.087196], [0.013, 550, 0.10005], [0.013, 750, 0.13644], [0.013, 950, 0.17282], [0.013, 1150, 0.2092], [0.013, 850, 0.15463], [0.013, 550, 0.07147], [0.013, 750, 0.09745], [0.013, 950, 0.

In [12]:
from sklearn.model_selection import train_test_split
training_input,validation_input,training_output,validation_output = train_test_split(xarray,
yarray, test_size=0.25, random_state=13)
# print to check the shape of training and validation set
training_input= np.array(training_input)#[:,[1,2,3]])
training_output= np.array(training_output)
validation_input= np.array(validation_input)#[:,[1,2,3]])
validation_output= np.array(validation_output)

print(validation_input)

xarray=training_input
yarray=training_output


[[1.18181818 0.88235294 1.05180788]
 [0.72727273 1.11764706 1.14786832]
 [1.         0.88235294 1.24554776]
 [1.18181818 1.35294118 1.25418241]
 [0.72727273 0.64705882 0.66454398]
 [0.72727273 0.64705882 0.36913114]
 [1.18181818 1.         1.66896924]
 [1.         1.         1.00809498]
 [1.18181818 1.35294118 1.61252024]
 [0.72727273 1.35294118 1.38909876]
 [1.         1.35294118 1.36427415]
 [1.         1.         1.41176471]
 [1.18181818 0.64705882 0.59989207]]


In [13]:
# define neural network model
#As seen below, we have created four dense layers.
#A dense layer is a layer in neural network that’s fully connected.
#In other words, all the neurons in one layer are connected to all other neurons in the next layer.
#In the first layer, we need to provide the input shape, which is 1 in our case.
#The activation function we have chosen is elu, which stands for exponential linear unit. .
from keras import backend as K
#initialize weights with values between -0.2 and 0.5
initializer = keras.initializers.RandomUniform(minval= -0.2, maxval=0.5)
model = keras.Sequential([
keras.layers.Dense(6, activation=K.elu, input_shape=[3], kernel_initializer=initializer),
keras.layers.Dense(8, activation=K.elu, kernel_initializer=initializer),
keras.layers.Dense(12, activation=K.elu, kernel_initializer=initializer),
keras.layers.Dense(16, activation=K.elu, kernel_initializer=initializer),
keras.layers.Dense(8, activation=K.elu, kernel_initializer=initializer),
keras.layers.Dense(2, kernel_initializer=initializer)
])

In [20]:
#We’re using RMSprop as our optimizer here. RMSprop stands for Root Mean Square Propagation.
#It’s one of the most popular gradient descent optimization algorithms for deep learning networks.
#RMSprop is an optimizer that’s reliable and fast.
#We’re compiling the mode using the model.compile function. The loss function used here
#is mean squared error. After the compilation of the model, we’ll use the fit method with ~500 epochs.
#Number of epochs can be varied.
#from tf.keras import optimizers
rms = keras.optimizers.RMSprop(0.01)
model.compile(loss='mean_absolute_error',optimizer=rms)

In [23]:
#After the compilation of the model, we’ll use the fit method with 500 epochs.
#I started with epochs value of 100 and then tested the model after training.
#The prediction was not that good. Then I modified the number of epochs to 200 and tested the model again.
#Accuracy had improved slightly, but figured I’d give it one more try. Finally, at 500 epochs
#I found acceptable prediction accuracy.
#The fit method takes three parameters; namely, x, y, and number of epochs.
#During model training, if all the batches of data are seen by the model once,
#we say that one epoch has been completed.
# Add an early stopping callback
es = keras.callbacks.EarlyStopping(
monitor='loss',
mode='min',
patience = 80,
restore_best_weights = True,
verbose=1)
# Add a checkpoint where loss is minimum, and save that model
mc = keras.callbacks.ModelCheckpoint('best_model.SB', monitor='loss',
mode='min', verbose=1, save_best_only=True)
historyData = model.fit(xarray,yarray,epochs=800,callbacks=[es])
loss_hist = historyData.history['loss']
#The above line will return a dictionary, access it's info like this:
best_epoch = np.argmin(historyData.history['loss']) + 1
print ('best epoch = ', best_epoch)
print('smallest loss =', np.min(loss_hist))
model.save('./best_model')

Epoch 1/800
2/2 [==============================] - 0s 3ms/step - loss: 0.0309
Epoch 2/800
2/2 [==============================] - 0s 0s/step - loss: 0.0351
Epoch 3/800
2/2 [==============================] - 0s 3ms/step - loss: 0.0444
Epoch 4/800
2/2 [==============================] - 0s 5ms/step - loss: 0.0341
Epoch 5/800
2/2 [==============================] - 0s 1ms/step - loss: 0.0313
Epoch 6/800
2/2 [==============================] - 0s 4ms/step - loss: 0.0551
Epoch 7/800
2/2 [==============================] - 0s 0s/step - loss: 0.0413
Epoch 8/800
2/2 [==============================] - 0s 3ms/step - loss: 0.0317
Epoch 9/800
2/2 [==============================] - 0s 0s/step - loss: 0.0361
Epoch 10/800
2/2 [==============================] - 0s 1ms/step - loss: 0.0366
Epoch 11/800
2/2 [==============================] - 0s 0s/step - loss: 0.0333
Epoch 12/800
2/2 [==============================] - 0s 0s/step - loss: 0.0650
Epoch 13/800
2/2 [==============================] - 0s 0s/step - l

In [18]:
# This line of code can be used to reconstruct the saved model.
recon_model = keras.models.load_model("best_model")
# the name of the model is now "recon_model". You can then use this model to do predictions for comparisons.
# See the previous project for code to do the comparisons.
# NOTE: If you get an error message when trying to run with the line
# recon_model = tf.keras.models.load_model("best_model")
# try running prediction calculations with model.predict() (as in the code for project 2)
# with the line recon_model = tf.keras.models.load_model("best_model") removed.
# That may avoid the error