In [5]:
'''>>>>> start CodeP4.1F23
V.P. Carey ME249, Fall 2023
Keras Neural Network Modeling '''
#import useful packages
import keras
import pandas as pd
from keras.models import Sequential
import numpy as np
import keras.backend as kb
import tensorflow as tf
#the following 2 lines are only needed for Mac OS machines
import os
os.environ['KMP_DUPLICATE_LIB_OK']='True'
# define meadian values of input variables - add your values here

import statistics
import numpy
xdata = []
ydata = []
#xdata.append([ Di(m), qoflux (kW/m^2), exit quality, max wall temperature (deg C)])
xdata.append([0.008, 550, 0.525, 306.7])
xdata.append([0.008, 650, 0.525, 298.5])
xdata.append([0.008, 750, 0.525, 294.2])
xdata.append([0.008, 850, 0.525, 290.2])
xdata.append([0.008, 950, 0.524, 286.9])
xdata.append([0.008, 1050, 0.524, 284.1])
xdata.append([0.008, 1150, 0.525, 281.7])
xdata.append([0.008, 850, 0.524, 290.31])
xdata.append([0.008, 550, 0.734, 307.9])
xdata.append([0.008, 750, 0.735, 295.5])
xdata.append([0.008, 950, 0.735, 287.8])
xdata.append([0.008, 1050, 0.735, 285.0])
xdata.append([0.008, 1150, 0.735, 282.5])
xdata.append([0.008, 850, 0.734, 291.3])
xdata.append([0.008, 550, 0.945, 308.6])
xdata.append([0.008, 750, 0.945, 296.2])
xdata.append([0.008, 950, 0.945, 288.5])
xdata.append([0.008, 1150, 0.945, 283.1])
xdata.append([0.008, 850, 0.945, 291.9])
xdata.append([0.011, 550, 0.525, 328.0])
xdata.append([0.011, 750, 0.525, 311.2])
xdata.append([0.011, 950, 0.525, 300.8])
xdata.append([0.011, 1150, 0.525, 293.6])
xdata.append([0.011, 850, 0.525, 305.5])
xdata.append([0.011, 550, 0.735, 329.6])
xdata.append([0.011, 750, 0.735, 312.6])
xdata.append([0.011, 950, 0.735, 302.0])
xdata.append([0.011, 1050, 0.735, 299.4])
xdata.append([0.011, 1150, 0.735, 294.8])
xdata.append([0.011, 850, 0.735, 306.8])
xdata.append([0.011, 550, 0.945, 330.7])
xdata.append([0.011, 750, 0.945, 313.6])
xdata.append([0.011, 950, 0.944, 302.9])
xdata.append([0.011, 1150, 0.945, 295.6])
xdata.append([0.011, 850, 0.944, 307.7])
xdata.append([0.011, 700, 0.734, 324.7])
xdata.append([0.013, 550, 0.525, 342.2])
xdata.append([0.013, 750, 0.524, 322.3])
xdata.append([0.013, 950, 0.524, 310.0])
xdata.append([0.013, 1150, 0.525, 301.6])
xdata.append([0.013, 850, 0.524, 315.5])
xdata.append([0.013, 550, 0.734, 344.1])
xdata.append([0.013, 750, 0.735, 324.0])
xdata.append([0.013, 950, 0.735, 311.5])
xdata.append([0.013, 1050, 0.735, 306.3])
xdata.append([0.013, 1150, 0.735, 302.9])
xdata.append([0.013, 850, 0.734, 317.1])
xdata.append([0.013, 550, 0.945, 345.3])
xdata.append([0.013, 750, 0.944, 325.1])
xdata.append([0.013, 950, 0.944, 312.5])
xdata.append([0.013, 1150, 0.945, 303.9])
xdata.append([0.013, 850, 0.945, 318.2])

#data.append([mdot (kg/s)])
ydata.append([0.06157])
ydata.append([0.07269])
ydata.append([0.08396])
ydata.append([0.09347])
ydata.append([0.10635])
ydata.append([0.11521])
ydata.append([0.1287])
ydata.append([0.09516])
ydata.append([0.04398])
ydata.append([0.05997])
ydata.append([0.07596])
ydata.append([0.08343])
ydata.append([0.0919])
ydata.append([0.06797])
ydata.append([0.0342])
ydata.append([0.04664])
ydata.append([0.05908])
ydata.append([0.0715])
ydata.append([0.05286])
ydata.append([0.0846])
ydata.append([0.1154])
ydata.append([0.1462])
ydata.append([0.177])
ydata.append([0.1308])
ydata.append([0.06047])
ydata.append([0.08246])
ydata.append([0.1044])
ydata.append([0.1134])
ydata.append([0.1264])
ydata.append([0.0934])
ydata.append([0.047])
ydata.append([0.06413])
ydata.append([0.08124])
ydata.append([0.09834])
ydata.append([0.072691])
ydata.append([0.087196])
ydata.append([0.10005])
ydata.append([0.13644])
ydata.append([0.17282])
ydata.append([0.2092])
ydata.append([0.15463])
ydata.append([0.07147])
ydata.append([0.09745])
ydata.append([0.12344])
ydata.append([0.13302])
ydata.append([0.1494])
ydata.append([0.11045])
ydata.append([0.05558])
ydata.append([0.0758])
ydata.append([0.09601])
ydata.append([0.1162])
ydata.append([0.0859])
xarray= numpy.array(xdata)
yarray= numpy.array(ydata)
print (xdata)
print (xarray)
print (ydata)
print (yarray)

#convert to:
# median values of output variables
ND=len(xarray)
Diall = [row[0] for row in xdata]
Dimed=statistics.median(Diall)
q0all = [row[1] for row in xdata]
q0med=statistics.median(q0all)
xeall = [row[2] for row in xdata]
xemed=statistics.median(xeall)
Twall = [row[3] for row in xdata]
Twmed=statistics.median(Twall)

mall = [row[0] for row in ydata]
mmed=statistics.median(mall)

xdata = []
ydata = []
for i in range(ND):
    xdata.append([xarray[i,0]/Dimed,xarray[i,1]/q0med,xarray[i,2]/xemed,xarray[i,3]/Twmed])
    ydata.append([yarray[i,0]/mmed])

xarray= np.array(xdata)
yarray= np.array(ydata)

#print (yarray)

data_inputs = np.array(xdata)
data_outputs = np.array(ydata)

[[0.008, 550, 0.525, 306.7], [0.008, 650, 0.525, 298.5], [0.008, 750, 0.525, 294.2], [0.008, 850, 0.525, 290.2], [0.008, 950, 0.524, 286.9], [0.008, 1050, 0.524, 284.1], [0.008, 1150, 0.525, 281.7], [0.008, 850, 0.524, 290.31], [0.008, 550, 0.734, 307.9], [0.008, 750, 0.735, 295.5], [0.008, 950, 0.735, 287.8], [0.008, 1050, 0.735, 285.0], [0.008, 1150, 0.735, 282.5], [0.008, 850, 0.734, 291.3], [0.008, 550, 0.945, 308.6], [0.008, 750, 0.945, 296.2], [0.008, 950, 0.945, 288.5], [0.008, 1150, 0.945, 283.1], [0.008, 850, 0.945, 291.9], [0.011, 550, 0.525, 328.0], [0.011, 750, 0.525, 311.2], [0.011, 950, 0.525, 300.8], [0.011, 1150, 0.525, 293.6], [0.011, 850, 0.525, 305.5], [0.011, 550, 0.735, 329.6], [0.011, 750, 0.735, 312.6], [0.011, 950, 0.735, 302.0], [0.011, 1050, 0.735, 299.4], [0.011, 1150, 0.735, 294.8], [0.011, 850, 0.735, 306.8], [0.011, 550, 0.945, 330.7], [0.011, 750, 0.945, 313.6], [0.011, 950, 0.944, 302.9], [0.011, 1150, 0.945, 295.6], [0.011, 850, 0.944, 307.7], [0.011, 7

In [79]:
from sklearn.model_selection import train_test_split
training_input,validation_input,training_output,validation_output = train_test_split(xarray,
yarray, test_size=0.25, random_state=13)
# print to check the shape of training and validation set
training_input= np.array(training_input)#[:,[1,2,3]])
training_output= np.array(training_output)
validation_input= np.array(validation_input)#[:,[1,2,3]])
validation_output= np.array(validation_output)

print(validation_input)

xarray=training_input
yarray=training_output


[[1.         0.64705882 1.28571429 1.08532983]
 [1.         0.64705882 1.         1.08171972]
 [1.18181818 1.11764706 0.71292517 1.01739416]
 [0.72727273 1.23529412 1.         0.93534624]
 [1.18181818 1.11764706 1.28435374 1.02559895]
 [0.72727273 0.88235294 1.         0.96980637]
 [0.72727273 0.88235294 1.28571429 0.97210371]
 [1.         1.35294118 1.28571429 0.97013456]]


In [86]:
# define neural network model
#As seen below, we have created four dense layers.
#A dense layer is a layer in neural network that’s fully connected.
#In other words, all the neurons in one layer are connected to all other neurons in the next layer.
#In the first layer, we need to provide the input shape, which is 1 in our case.
#The activation function we have chosen is elu, which stands for exponential linear unit. .
from keras import backend as K
#initialize weights with values between -0.2 and 0.5
initializer = keras.initializers.RandomUniform(minval= -0.2, maxval=0.5)
model = keras.Sequential([
keras.layers.Dense(6, activation=K.elu, input_shape=[4], kernel_initializer=initializer),
keras.layers.Dense(8, activation=K.elu, kernel_initializer=initializer),
keras.layers.Dense(12, activation=K.elu, kernel_initializer=initializer),
keras.layers.Dense(16, activation=K.elu, kernel_initializer=initializer),
keras.layers.Dense(8, activation=K.elu, kernel_initializer=initializer),
keras.layers.Dense(2, kernel_initializer=initializer)
])

In [87]:
#We’re using RMSprop as our optimizer here. RMSprop stands for Root Mean Square Propagation.
#It’s one of the most popular gradient descent optimization algorithms for deep learning networks.
#RMSprop is an optimizer that’s reliable and fast.
#We’re compiling the mode using the model.compile function. The loss function used here
#is mean squared error. After the compilation of the model, we’ll use the fit method with ~500 epochs.
#Number of epochs can be varied.
#from tf.keras import optimizers
rms = keras.optimizers.RMSprop(0.01)
model.compile(loss='mean_absolute_error',optimizer=rms)

In [89]:
#After the compilation of the model, we’ll use the fit method with 500 epochs.
#I started with epochs value of 100 and then tested the model after training.
#The prediction was not that good. Then I modified the number of epochs to 200 and tested the model again.
#Accuracy had improved slightly, but figured I’d give it one more try. Finally, at 500 epochs
#I found acceptable prediction accuracy.
#The fit method takes three parameters; namely, x, y, and number of epochs.
#During model training, if all the batches of data are seen by the model once,
#we say that one epoch has been completed.
# Add an early stopping callback
es = keras.callbacks.EarlyStopping(
monitor='loss',
mode='min',
patience = 90,
restore_best_weights = True,
verbose=1)
# Add a checkpoint where loss is minimum, and save that model
mc = keras.callbacks.ModelCheckpoint('best_model.SB', monitor='loss',
mode='min', verbose=1, save_best_only=True)
historyData = model.fit(xarray,yarray,epochs=800,callbacks=[es])
loss_hist = historyData.history['loss']
#The above line will return a dictionary, access it's info like this:
best_epoch = np.argmin(historyData.history['loss']) + 1
print ('best epoch = ', best_epoch)
print('smallest loss =', np.min(loss_hist))
model.save('./best_model')

Epoch 1/800
1/1 [==============================] - 0s 2ms/step - loss: 0.0695
Epoch 2/800
1/1 [==============================] - 0s 1ms/step - loss: 0.1294
Epoch 3/800
1/1 [==============================] - 0s 1ms/step - loss: 0.1232
Epoch 4/800
1/1 [==============================] - 0s 0s/step - loss: 0.0612
Epoch 5/800
1/1 [==============================] - 0s 4ms/step - loss: 0.0748
Epoch 6/800
1/1 [==============================] - 0s 0s/step - loss: 0.1230
Epoch 7/800
1/1 [==============================] - 0s 1ms/step - loss: 0.1191
Epoch 8/800
1/1 [==============================] - 0s 0s/step - loss: 0.0651
Epoch 9/800
1/1 [==============================] - 0s 3ms/step - loss: 0.0831
Epoch 10/800
1/1 [==============================] - 0s 3ms/step - loss: 0.1253
Epoch 11/800
1/1 [==============================] - 0s 2ms/step - loss: 0.1124
Epoch 12/800
1/1 [==============================] - 0s 4ms/step - loss: 0.0692
Epoch 13/800
1/1 [==============================] - 0s 0s/step -

In [55]:
# This line of code can be used to reconstruct the saved model.
recon_model = keras.models.load_model("best_model")
# the name of the model is now "recon_model". You can then use this model to do predictions for comparisons.
# See the previous project for code to do the comparisons.
# NOTE: If you get an error message when trying to run with the line
# recon_model = tf.keras.models.load_model("best_model")
# try running prediction calculations with model.predict() (as in the code for project 2)
# with the line recon_model = tf.keras.models.load_model("best_model") removed.
# That may avoid the error